# Generated by Django 5.2 on 2025-05-04 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.CharField(choices=[('Cистемного проектування', 'Cистемного проектування'), ('Радіофізики та комп’ютерних технологій', 'Радіофізики та комп’ютерних технологій'), ('Радіоелектронних і комп’ютерних систем', 'Радіоелектронних і комп’ютерних систем'), ('Оптоелектроніки та інформаційних технологій', 'Оптоелектроніки та інформаційних технологій')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesis_topic', models.CharField(max_length=200, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('course', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('departament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.departament')),
                ('interests', models.ManyToManyField(blank=True, to='main.interest')),
            ],
        ),
    ]
